### ISSUE TITLE
bug/suggestions

### ISSUE THREAD

**Issue by sifte** [CodeWithSwastik/simon-says#2]
- bots can be eliminated for some reason

- ![image](https://user-images.githubusercontent.com/84506518/159172876-a7b643e5-d9f7-47e3-9801-70c25e06132c.png)
 what

**Comment by captainaraf** [comment]
> * bots can be eliminated for some reason
> * ![image](https://user-images.githubusercontent.com/84506518/159172876-a7b643e5-d9f7-47e3-9801-70c25e06132c.png)
>   what

Man I remember I added that 🤣 reaction
